language: python
python:
    - 3.6
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install --upgrade setuptools pip
    - pip install -f travis-wheels/wheelhouse --pre -e . coveralls
    - pip install 'tornado<5'  # Temporary workaround
    - python -m ipykernel.kernelspec --user
script:
    - nosetests --with-coverage --cover-package=jupyter_console jupyter_console
after_success:
    - coveralls
